name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      #----------------------------------------------
      # install root project, if required
      #----------------------------------------------
      - name: Install
        run: |
          pip install wagtail
      #----------------------------------------------
      #    Test
      #----------------------------------------------
      - name: Test with pytest
        run: |
          python runtests.py